from typing import TYPE_CHECKING

from virtbmc.api.rpc.client import Client
from virtbmc.api.rpc.server import Server

__all__ = ["Client", "Server"]

if TYPE_CHECKING:
    from typing import Optional, Tuple

    from virtbmc_core.types import Config as BmcConfig

    class _RPC:
        # fmt: off
        def app_init(self) -> None:...
        def bmc_create(self, bmc_config: BmcConfig) -> None:...
        def bmc_delete(self, name: str) -> None:...
        def bmc_start(self, name: str) -> None:...
        def bmc_stop(self, name: str) -> None:...
        def bmc_get(self, name: str) -> Optional[BmcConfig]:...
        def bmc_get_all(self) -> Tuple[BmcConfig, ...]:...
        # fmt: on
