from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Optional, Protocol, Tuple

    from virtbmc_core.types import Config as BmcConfig

    class Database(Protocol):
        # fmt: off
        def create(self, bmc_config: BmcConfig) -> None:...
        def read(self, name: str) -> Optional[BmcConfig]:...
        def delete(self, name: str) -> None:...
        def start(self, name: str) -> None:...
        def stop(self, name: str) -> None:...
        def get_active(self) -> Tuple[BmcConfig,...]:...
        def get_all(self) -> Tuple[BmcConfig]:...
        # fmt: on
