from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Iterator, Optional, Protocol

    from virtbmc_core.types import Config as BmcConfig

    class Database(Protocol):
        # fmt: off
        def create(self, bmc_config: BmcConfig) -> None:...
        def read(self, name: str) -> Optional[BmcConfig]:...
        def delete(self, name: str) -> None:...
        def start(self, name: str) -> None:...
        def stop(self, name: str) -> None:...
        def all(self) -> Iterator[BmcConfig]:...
        # fmt: on
