from typing import TYPE_CHECKING, Any, Mapping

if TYPE_CHECKING:
    from typing import Optional, Protocol, Tuple

    from virtbmc_core.types import Config as BmcConfig

    class Database(Protocol):
        # fmt: off
        def write(self, bmc_config: BmcConfig) -> None:...
        def read(self, name: str) -> Optional[BmcConfig]:...
        def delete(self, name: str) -> None:...
        def update(self, name: str, settings: Mapping[str, Any]) -> None:...
        def get_active(self) -> Tuple[BmcConfig,...]:...
        def get_all(self) -> Tuple[BmcConfig]:...
        # fmt: on
