# Adapted from pyghmi.ipmi.private.constants - Copyright 2013 IBM Corporation

from __future__ import annotations

from enum import IntEnum, unique


@unique
class IPMI_COMPLETION_CODES(IntEnum):
    SUCCESS = 0x00
    NODE_BUSY = 0xC0
    INVALID_COMMAND = 0xC1
    INVALID_COMMAND_FOR_GIVEN_LUN = 0xC2
    TIMEOUT_WHILE_PROCESSING_COMMAND = 0xC3
    OUT_OF_STORAGE_SPACE_ON_BMC = 0xC4
    RESERVATION_CANCELED_OR_INVALID_RESERVATION_ID = 0xC5
    REQUEST_DATA_TRUNCATED = 0xC6
    REQUEST_DATA_LENGTH_INVALID = 0xC7
    REQUEST_DATA_FIELD_LENGTH_LIMIT_EXCEEDED = 0xC8
    PARAMETER_OUT_OF_RANGE = 0xC9
    CANNOT_RETURN_NUMBER_OF_REQUESTED_DATA_BYTES = 0xCA
    REQUESTED_SENSOR_DATA_OR_RECORD_NOT_PRESENT = 0xCB
    INVALID_DATA_FIELD_IN_REQUEST = 0xCC
    COMMAND_ILLEGAL_FOR_SPECIFIED_SENSOR_OR_RECORD_TYPE = 0xCD
    COMMAND_RESPONSE_COULD_NOT_BE_PROVIDED = 0xCE
    CANNOT_EXECUTE_DUPLICATED_REQUEST = 0xCF
    SDR_REPOSITORY_IN_UPDATE_MODE = 0xD0
    DEVICE_IN_FIRMWARE_UPDATE_MODE = 0xD1
    BMC_INITIALIZATION_IN_PROGRESS = 0xD2
    INTERNAL_DESTINATION_UNAVAILABLE = 0xD3
    INSUFFICIENT_PRIVILEGE_LEVEL_OR_FIRMWARE_FIREWALL = 0xD4
    COMMAND_NOT_SUPPORTED_IN_PRESENT_STATE = 0xD5
    CANNOT_EXECUTE_COMMAND_BECAUSE_SUBFUNCTION_DISABLED_OR_UNAVAILABLE = 0xD6
    UNSPECIFIED = 0xFF
    TIMEOUT = 0xFFFF  # not ipmi, but used internally


class BOOT_DEVICES(IntEnum):
    NET = 4
    NETWORK = 4
    PXE = 4
    HD = 8
    SAFE = 0xC
    CD = 0x14
    CDROM = 0x14
    OPTICAL = 0x14
    DVD = 0x14
    FLOPPY = 0x3C
    USB = 0x3C
    DEFAULT = 0x0
    SETUP = 0x18
    BIOS = 0x18
    F1 = 0x18
